### ISSUE TITLE
content: Progressive Web App Checklist

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1349]
**Author**: @Snugug 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1Tgm4boA7VBEowsNjqoT_O4Tdc7eqnthftbLN62YwZ4U/edit)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #2051
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by petele** [comment]
@jpmedley - this one is ready for it's first review.

**Comment by Snugug** [comment]
Ping on getting this content reviewed, esp, now that #1454 has landed (why and how in each section go into the expandable area)

**Comment by robdodson** [comment]
Assigning to @jpmedley to review

**Comment by kaycebasques** [comment]
@jpmedley this is ready for your review

**Comment by jpmedley** [comment]
@Snugug I have reviewed your draft and made a number of suggestions. As usual, your copy is exceptionally clean of typos and such. I've made some stylistic suggestions with explanations. Ping me if you have questions.

**Comment by Snugug** [comment]
TY will review when I've got a moment of free time

**Comment by Snugug** [comment]
Hey all, just giving this a post-Thanksgiving bump. I've answered the outstanding comments @jpmedley gave in the doc

**Comment by robdodson** [comment]
@carolrivero it looks like this was  moved to  the  week of January 8th. Just confirming  that for @Snugug so he has insight into the progress.

**Comment by carolrivero** [comment]
@robdodson - Thanks, Rob. I wish there was a cc field in GH ;-) @Snugug - please confirm if this new date works for you.

**Comment by Snugug** [comment]
As long as that release also includes #1346, #1345, and #1450 so we can launch the section then, that sounds good to me.

**Comment by carolrivero** [comment]
Thanks, @Snugug. All issues you linked have been updated w/ a milestone of Sprint 2020-01-08.

**Comment by petele** [comment]
This doc is ready to convert - I'll move it to markdown.
