### ISSUE TITLE
Create an reusable component for Origin Trials instructions

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1618]
## Tasks

- [ ] Update the Instruction component
- [ ] Update https://web.dev/badging-api/#ot
- [ ] Update https://web.dev/sms-receiver-api-announcement
- [ ] Update https://web.dev//contact-picker/#origin-trial

## How to implement

1. Create an include like this: https://github.com/GoogleChrome/web.dev/blob/master/src/site/_includes/content/origin-trials.njk

**Comment by petele** [comment]
It'd be great if there was a variable or something that I could set the URL to the specific origin trial, so when the widget is included, the URL links to the specific OT I'm referencing.

**Comment by kaycebasques** [comment]
@mfriesenhahn would you please verify that my "how to implement" instructions are correct, leave a comment if not, and then assign back to @jpmedley

**Comment by kaycebasques** [comment]
@robdodson can you advise on the best way to implement this (in [this comment](https://github.com/GoogleChrome/web.dev/pull/1614/files#r333145860) you seem to suggest an approach), and perhaps give @jpmedley some general instructions on how to implement (like I did in the first comment), and then assign to @jpmedley when it's ready for implementation

**Comment by robdodson** [comment]
@kaycebasques instead of using the isntruction component would you like for this content to be in an include? Similar to this one? https://github.com/GoogleChrome/web.dev/blob/master/src/site/_includes/content/origin-trials.njk

**Comment by kaycebasques** [comment]
@robdodson that SGTM

@jpmedley I got confirmation from Rob on the best way to implement this, so you can work on this whenever you like

**Comment by petele** [comment]
Typically we link directly to the OT in the standard block we use, and that link changes with each OT. If we can set a variable or something like that so the link works, I'd be happy for that to be an include.

**Comment by robdodson** [comment]
I think there's two ways to do this: includes or macros. They're pretty similar so I think it comes down to which syntax you prefer.

If you want to use includes you can do:

```
{% set ot = { url: 'https://google.com' } %}
{% include "content/origin-trial-signup.njk" %}
```

The include would contain:
```
Join <a href="{{ot.url}}">origin trial</a>
```

If you want to use macros you can do:

```
{% import "macros/origin-trials" as ot %}
{{ ot.signUp('https://google.com') }}
```

The macro would contain:
```
{% macro signUp(url) %}
Join <a href="{{url}}">origin trial</a>
{% endmacro %}
```

I guess the upside of macros is you can have more than one macro exported from a file. Do y'all have a preference either way?

**Comment by jpmedley** [comment]
Can a macro take more than one argument? We might want to do:

`Join the <a href="{{ot.url}}">{{ot.apiName}}</a> origin trial.`

**Comment by petele** [comment]
I personally would lean towards includes, adding multiple things exported from a single file doesn't seem like enough of a benefit to go that way.

**Comment by robdodson** [comment]
yeah a macro can take multiple arguments, or you can pass in an object. You can do the same with an include. The differences are pretty small. Sounds like an include is the way to go on this. @jpmedley did you want to take a shot at it or shall I? The [include docs are here](https://mozilla.github.io/nunjucks/templating.html#include) but they're pretty short. I think the example above is pretty much all you'd need.

**Comment by robdodson** [comment]
Actually, if it's ok, I can just do this since I'm already reviewing Pete's posts. I can update the PR for the badging icon post to use the include so y'all can review.

**Comment by robdodson** [comment]
Fixed in https://github.com/GoogleChrome/web.dev/pull/1614/commits/0764f80fa3e9064501a635cbc45bb5798cd93305

I'll rebase the other PRs to use this include.

**Comment by petele** [comment]
Score - thank you!

**Comment by petele** [comment]
BTW: this is also used in: #1652, #1622, and #1623
