### ISSUE TITLE
content: Add historical scoring info and deprecations for Lighthouse 6.0

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1630]
**Author**: @kaycebasques 
**Reviewer**: @paulirish 

**Tasks**

- [ ] Call out deprecations
  * Addressed in #1660 
- [ ] Add historical scoring to the Lighthouse scoring doc
  * Addressed in #1660

**Target publish date:** 2019-10-17 (Chrome 79 Branch Point)

- [x] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1660 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Please confirm who the reviewer is on this one. Thanks.

**Comment by kaycebasques** [comment]
@paulirish I wouldn't have it any other way. I'll write and you can review.

**Comment by kaycebasques** [comment]
@paulirish #1660 is my first pass, please leave feedback and then assign back to me

**Comment by kaycebasques** [comment]
Paul reviewed the PR 2 days ago, so next step is for me to incorporate feedback.
