### ISSUE TITLE
content: Update metrics tables and explanations

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1631]
**Author**: @kaycebasques 
**Reviewer**: @patrickhulce

**Context**

https://github.com/GoogleChrome/web.dev/issues/1344#issuecomment-524661106

**Tasks**

- [ ] The score table and explanations for metrics are off. Need to get a detailed review from Patrick.

**Target publish date:** 2019-10-17

- [ ] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
One (ambitious) possibility to address the ongoing problem of screenshot datedness: if we could embed the relevant piece of the actual LH UI on the page, that'd help! Don't know what the LoE would be for the LH team though.

Also, we'd need some automated notification when UI changes occur so any textual descriptions in the posts can be updated.

**Comment by mfriesenhahn** [comment]
I've marked the `dom-size` TODO as done. It does have a link: https://web.dev/dom-size

**Comment by carolrivero** [comment]
Please confirm who the reviewer is for this one. Thx.

**Comment by kaycebasques** [comment]
I should address this in Q4 but we don't need to ship this by CDS.

**Comment by carolrivero** [comment]
reprioritized to help w/ bandwidth for cds related posts.

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?
