### ISSUE TITLE
Learn Forms: pre-flight checklist

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#6233]
An issue for the things we don't want to forget at the end, add things to the list as we think of them.

- [x] Check sidebar order and sectioning is correct, and everything is linked in.
- [x] Check all links if they are correctly linked
- [x] #6183
- [x] Final read-through all content and raise PR for any final nits: Michael Scharnagl
- [ ] Final read-through all content and raise PR for any final nits: Sam Dutton
- [ ] Final read-through all content and raise PR for any final nits: Rachel Andrew
- [x] Final check if all CodePen embeds use the correct format (tab, height, ...): Michael Scharnagl
- [x] Set all CodePen demos to public: Michael Scharnagl
- [ ] Update all dates to go-live date
