### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#759]
- [ ] Make sure we have the same font families in our DevSite template.
- [ ] Compare codelab pages between beta and v1.
- [ ] Every page works in FF, Safari, Edge, Chrome.
- [ ] Step through pages in ChromeVox and VO.
- [x] Site has sitemap.xml (need to verify on staging).
- [x] Rev GA version.
- [x] Fix focus state on measure X button.
- [x] Fix wrapping on Learn page overview.
- [x] Test redirects on staging.
- [x] Analytics are working.
- [x] Every page works on mobile, tablet, desktop, large desktop.
- [x] On /learn, remove LH header and fix indentation on mobile.
- [x] Consider removing the blue active state.
- [x] Improve header button spacing on mobile.
- [x] Audit all tables.
- [x] Verify measure tool.
- [x] Every page has a title.
- [x] Every page has a description.
- [x] Every page has social meta tags.
- [x] Site has robots.txt.

**Comment by robdodson** [comment]
We launched soooooo closing this.
