### ISSUE TITLE
EPIC: Clean up all `-w` prefixed classes

### ISSUE THREAD

**Issue by mamieorine** [GoogleChrome/web.dev#9703]
Implementation follow-up issue for https://github.com/GoogleChrome/web.dev/issues/9650.

The `-w` prefixed for the inline classes are an artefact from the old system that need to be cleaned up.

- [x] https://github.com/GoogleChrome/web.dev/issues/9707
- [x] https://github.com/GoogleChrome/web.dev/issues/9709
- [x] https://github.com/GoogleChrome/web.dev/issues/9710
- [x] https://github.com/GoogleChrome/web.dev/issues/9711
- [x] https://github.com/GoogleChrome/web.dev/issues/9712
- [ ] https://github.com/GoogleChrome/web.dev/issues/9713
- [x] https://github.com/GoogleChrome/web.dev/issues/9706
